name: job-agent
channels:
  - conda-forge
dependencies:
  # --- core ---
  - python=3.12     
  # --- dev / quality ---
  - pytest
  - black
  - flake8
  - python-dotenv
  - pre-commit
  - pip             # let pip handle anything not in Conda
  - pip:
      - openai      