name: CI
on: 
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}    
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
      - name: Install package
        shell: bash -el {0}
        run: pip install -e .
      - name: Run tests
        shell: bash -el {0}
        run: pytest -q
      - name: Run pre-commit
        shell: bash -el {0}
        run: pre-commit run --all-files --show-diff-on-failure 
