name: Daily Job Agent

"on":
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

concurrency:
  group: job-agent
  cancel-in-progress: true

jobs:
  run-agent:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true

      - name: Install package
        shell: bash -el {0}
        run: pip install -e .

      - name: Run agent once
        shell: bash -el {0}
        run: python -m app.job_search_llm_agent.agent

